### ISSUE TITLE
Update doc.maniaplanet.com

### ISSUE THREAD

**Issue by codecat** [maniaplanet/documentation#73]
Latest commit here was [8 days ago](https://github.com/maniaplanet/documentation/commit/282b8e7afa735c9f3b9b78e2f6da3f3224644964) but this is not reflected on [this page](https://doc.maniaplanet.com/web-services/oauth2).

**Comment by magnetik** [comment]
Yep I will add this ass a weekly routine. I'll update after your pull request is merged :)
