### ISSUE TITLE
Actually write a documentation that helps

### ISSUE THREAD

**Issue by ThaumicTom** [maniaplanet/documentation#99]
Example: https://doc.maniaplanet.com/mesh-modeler 

It's just one page

**Comment by MartiniDry** [comment]
Hello @ThaumicTom! I've had the same problem than you, I gonna learn this editor my own way then I'll write this tutorial, we'll see if it can be added to the website.

I'm disappointed that such a useful ManiaPlanet tool contains so little documentation on it 😢
